# Week 3 - Data Cleaning using Pandas

**Skill Nexis Data Analyst Internship**

Author: Aayush Aggarwal

# Import Libraries

In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the Dataset

In [23]:
df = pd.read_csv("../Dataset/data.csv")

# Display the Dataset

In [24]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

# First Five Rows

In [25]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

# Last Five Rows

In [26]:
df.tail()

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

# Dataset Shape

In [31]:
df.shape

(32, 5)

# Column Names

In [32]:
df.columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='str')

# Dataset Information

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     str
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), str(1)
memory usage: 1.4 KB

# Statistical Summary

In [28]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

# Missing Values

In [30]:
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

# Duplicate Records

In [33]:
df.duplicated().sum()

np.int64(1)

# Data Types

In [34]:
df.dtypes

Duration      int64
Date            str
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

# Check Duplicate Rows

In [35]:
df[df.duplicated()]

    Duration          Date  Pulse  Maxpulse  Calories
12        60  '2020/12/12'    100       120     250.7

# Remove Duplicate Rows

In [36]:
df = df.drop_duplicates()

In [37]:
df.duplicated().sum()

np.int64(0)

In [38]:
df.shape

(31, 5)

# Rows with Missing Date

In [39]:
df[df["Date"].isnull()]

    Duration Date  Pulse  Maxpulse  Calories
22        45  NaN    100       119     282.0

In [40]:
df = df.dropna(subset=["Date"])

# Fill Missing Calories

In [41]:
df["Calories"].median()

np.float64(300.0)

In [42]:
df["Calories"] = df["Calories"].fillna(df["Calories"].median())

In [43]:
df.isnull().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [44]:
df.shape

(30, 5)

# Verifying Data Types

In [45]:
df.dtypes

Duration      int64
Date            str
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [47]:
df["Date"]

0     '2020/12/01'
1     '2020/12/02'
2     '2020/12/03'
3     '2020/12/04'
4     '2020/12/05'
5     '2020/12/06'
6     '2020/12/07'
7     '2020/12/08'
8     '2020/12/09'
9     '2020/12/10'
10    '2020/12/11'
11    '2020/12/12'
13    '2020/12/13'
14    '2020/12/14'
15    '2020/12/15'
16    '2020/12/16'
17    '2020/12/17'
18    '2020/12/18'
19    '2020/12/19'
20    '2020/12/20'
21    '2020/12/21'
23    '2020/12/23'
24    '2020/12/24'
25    '2020/12/25'
26        20201226
27    '2020/12/27'
28    '2020/12/28'
29    '2020/12/29'
30    '2020/12/30'
31    '2020/12/31'
Name: Date, dtype: str

In [48]:
df["Date"].unique()

<StringArray>
[''2020/12/01'', ''2020/12/02'', ''2020/12/03'', ''2020/12/04'',
 ''2020/12/05'', ''2020/12/06'', ''2020/12/07'', ''2020/12/08'',
 ''2020/12/09'', ''2020/12/10'', ''2020/12/11'', ''2020/12/12'',
 ''2020/12/13'', ''2020/12/14'', ''2020/12/15'', ''2020/12/16'',
 ''2020/12/17'', ''2020/12/18'', ''2020/12/19'', ''2020/12/20'',
 ''2020/12/21'', ''2020/12/23'', ''2020/12/24'', ''2020/12/25'',
     '20201226', ''2020/12/27'', ''2020/12/28'', ''2020/12/29'',
 ''2020/12/30'', ''2020/12/31'']
Length: 30, dtype: str

# Convert Date Column to Datetime

In [49]:
df["Date"] = pd.to_datetime(df["Date"], format="mixed")

In [50]:
df.dtypes

Duration             int64
Date        datetime64[us]
Pulse                int64
Maxpulse             int64
Calories           float64
dtype: object

# Feature Engineering

## 1. Calories Burned Per Minute

In [51]:
df["Calories_per_Minute"] = (df["Calories"] / df["Duration"]).round(2)

In [52]:
df['Calories_per_Minute']

0     6.82
1     7.98
2     5.67
3     6.28
4     9.02
5     5.00
6     6.23
7     0.56
8     6.50
9     4.48
10    5.49
11    4.18
13    5.76
14    6.32
15    4.58
16    3.59
17    5.00
18    6.67
19    5.38
20    5.40
21    6.07
23    5.00
24    5.47
25    5.58
26    4.17
27    4.02
28    5.00
29    4.67
30    6.34
31    4.05
Name: Calories_per_Minute, dtype: float64

## 2. Pulse Difference

In [53]:
df["Pulse_Difference"] = df["Maxpulse"] - df["Pulse"]

In [54]:
df['Pulse_Difference']

0     20
1     28
2     32
3     66
4     31
5     25
6     26
7     30
8     24
9     26
10    44
11    20
13    22
14    28
15    25
16    22
17    20
18    22
19    20
20    28
21    23
23   -29
24    27
25    24
26    20
27    26
28    29
29    32
30    27
31    23
Name: Pulse_Difference, dtype: int64

## 3. Workout Intensity

In [55]:
df["Workout_Intensity"] = df["Pulse"].apply(
    lambda x: "High" if x >= 120 else "Normal"
)

In [56]:
df['Workout_Intensity']

0     Normal
1     Normal
2     Normal
3     Normal
4     Normal
5     Normal
6     Normal
7     Normal
8     Normal
9     Normal
10    Normal
11    Normal
13    Normal
14    Normal
15    Normal
16    Normal
17    Normal
18    Normal
19    Normal
20    Normal
21    Normal
23      High
24    Normal
25    Normal
26    Normal
27    Normal
28    Normal
29    Normal
30    Normal
31    Normal
Name: Workout_Intensity, dtype: str

# Display the Updated Dataset

In [57]:
df.head()

,Duration,Date,Pulse,Maxpulse,Calories,Calories_per_Minute,Pulse_Difference,Workout_Intensity
0,60,2020-12-01,110,130,409.1,6.82,20,Normal
1,60,2020-12-02,117,145,479.0,7.98,28,Normal
2,60,2020-12-03,103,135,340.0,5.67,32,Normal
3,45,2020-12-04,109,175,282.4,6.28,66,Normal
4,45,2020-12-05,117,148,406.0,9.02,31,Normal

# Exploratory Data Analysis (EDA)

In [58]:
print("Total Workouts:", len(df))

Total Workouts: 30

In [59]:
print("Average Calories Burned:", round(df["Calories"].mean(), 2))

Average Calories Burned: 306.92

In [60]:
print("Average Pulse:", round(df["Pulse"].mean(), 2))

Average Pulse: 103.73

In [61]:
print("Maximum Calories Burned:", df["Calories"].max())

Maximum Calories Burned: 479.0

In [62]:
print("Minimum Calories Burned:", df["Calories"].min())

Minimum Calories Burned: 195.1

In [63]:
df["Workout_Intensity"].value_counts()

Workout_Intensity
Normal    29
High       1
Name: count, dtype: int64

# Save the Cleaned Dataset

In [64]:
df.to_csv("../Results/cleaned_data.csv", index=False)

# Conclusion

The dataset was successfully cleaned by:

- Removing duplicate records.
- Handling missing values.
- Converting the Date column to datetime format.
- Creating new features for deeper analysis.
- Performing exploratory data analysis.
- Visualizing important patterns using charts.

The cleaned dataset is now ready for further analysis or machine learning applications.